openapi: 3.0.0
info:
  title: Info-OnInfo
  description: ONDC Network NPs info
  version: 1.0.0
security:
  - SubscriberAuth: []
paths:
  /info:
    post:
      tags:
        - Info Requester
        - Info Provider
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                context:
                  $ref: "#/components/schemas/Context"
                message:
                  type: object
                  properties:
                    intent:
                      $ref: "#/components/schemas/Intent"
      responses:
        "200":
          description: Acknowledgement of message received
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: object
                    properties:
                      ack:
                        $ref: "#/components/schemas/Ack"
                    required:
                      - ack
                  error:
                    $ref: "#/components/schemas/Error"
                required:
                  - message
  /on_info:
    post:
      tags:
        - Info Requester
        - Info Provider
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                context:
                  $ref: "#/components/schemas/Context"
                message:
                  type: object
                  properties:
                    info:
                      $ref: "#/components/schemas/Info"
      responses:
        "200":
          description: Acknowledgement of message received
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: object
                    properties:
                      ack:
                        $ref: "#/components/schemas/Ack"
                    required:
                      - ack
                  error:
                    $ref: "#/components/schemas/Error"
                required:
                  - message
components:
  securitySchemes:
    SubscriberAuth:
      type: apiKey
      in: header
      name: Authorization
      description: 'Signature of message body using BAP or BPP subscriber''s signing public key. <br/><br/>Format:<br/><br/><code>Authorization : Signature keyId="{subscriber_id}|{unique_key_id}|{algorithm}",algorithm="ed25519",created="1606970629",expires="1607030629",headers="(created) (expires) digest",signature="Base64(signing string)"</code>'
  schemas:
    Ack:
      type: object
      properties:
        status:
          type: string
          enum:
            - ACK
            - NACK
        tags:
          type: array
          items:
            $ref: "#/components/schemas/TagGroup"
    Context:
      type: object
      properties:
        domain:
          type: string
        country:
          type: string
        city:
          type: string
        action:
          type: string
        core_version:
          type: string
        bap_id:
          type: string
        bap_uri:
          type: string
        bpp_id:
          type: string
        bpp_uri:
          type: string
        transaction_id:
          type: string
        message_id:
          type: string
        timestamp:
          type: string
          format: date-time
        key:
          type: string
        ttl:
          type: string
    City:
      description: Codification of city code will be using the std code of the city e.g. for Bengaluru, city code is 'std:080'
      type: string
    Descriptor:
      description: Describes the description of a real-world object.
      type: object
      properties:
        code:
          type: string
          enum:
            - INFO

    Entity:
      type: object
      properties:
        gst:
          type: object
          properties:
            legal_entity_name:
              type: string
            business_address:
              type: string
            city_code:
              type: array
              items:
                $ref: "#/components/schemas/City"
            gst_no:
              type: string
        pan:
          type: object
          properties:
            name_as_per_pan:
              type: string
              description: This shall be used to match the name as per PAN with Income Tax Department
            pan_no:
              type: string
              description: Permanent Account Number issued by Income Tax Department. First five alphabets followed by four numeric followed by one alphabet
            date_of_incorporation:
              type: string
              format: date
              description: DD/MM/YYYY format
        name_of_authorised_signatory:
          type: string
        address_of_authorised_signatory:
          type: string
        email_id:
          type: string
        mobile_no:
          type: number
        country:
          type: string
          description: Country code as per ISO 3166-1 and ISO 3166-2 format
        bank_details:
          type: object
          properties:
            account_no:
              type: string
            ifsc_code:
              type: string
            beneficiary_name:
              type: string
            bank_name:
              type: string
            branch_name:
              type: string
    Error:
      type: object
      properties:
        code:
          type: string
        paths:
          type: string
        message:
          type: string
    Info:
      type: object
      properties:
        type:
          type: string
          enum:
            - BAP
            - BPP
        entity:
          $ref: "#/components/schemas/Entity"
    Intent:
      description: Intent of a user. Used for searching for services.
      properties:
        descriptor:
          $ref: "#/components/schemas/Descriptor"
    Tag:
      type: object
      properties:
        code:
          type: string
        value:
          type: string
    TagGroup:
      type: object
      properties:
        code:
          type: string
        list:
          type: array
          items:
            $ref: "#/components/schemas/Tag"
